import Toast from "./components/atoms/Toast";
import QueryContext from "./contexts/QueryContext";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toast />
        <QueryContext>
          <div className="min-h-full">
            <header className="border-b border-gray-200 bg-white">
              <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
                <div className="flex h-16 justify-between">
                  <div className="flex items-center">
                    <div className=" text-lg md:text-3xl font-semibold">
                      Lani Blog
                    </div>
                  </div>
                </div>
              </div>
            </header>
            {children}
          </div>
        </QueryContext>
      </body>
    </html>
  );
}